services:
  # ----- C O N T E N T   M O D E R A T O R -----
  content-moderator:
    build: ./services/content-moderator
    container_name: ${CONTENT_MODERATOR_CONTAINER_NAME}
    ports:
      - "${CONTENT_MODERATOR_PORT}:${CONTENT_MODERATOR_PORT}"
    networks:
      - app-network
    volumes:
      - ./services/content-moderator/src:/app/src
    environment:
      - NODE_ENV=dev
      - PROJECT_NAME=${CONTENT_MODERATOR_DOCUMENTATION_TITLE}
      - PORT=${CONTENT_MODERATOR_PORT}
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}

  content-moderator-python:
    build: ./content-moderator-python
    container_name: content-moderator-python
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
